config/routes.rb
App3::Application.routes.draw do
  devise_for :users

  resources :friendlists
  
  resources :posts do
    collection do
      post:add_comment
      post:add_likepost
      post:add_likecomment
      get:userinfo
      get:friendinfo
    end
   
    resources :comments do
      collection do
      end
    end
  end
  
  resources :users do
    collection do
      get:welcome
      get:getrequest
      get:replyrequest
      get:deleterequest
      get:sendrequest
      get:edituser
      put:updateuser
    end
    
    member do
      get:sendrequest
      get:getrequest
      get:replyrequest
      get:deleterequest
    end
  end
    root :to => 'users#home'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  attr_accessible :friend_id, :friend_status, :user_id
  has_and_belongs_to_many :users ,:class_name => 'User', :foreign_key => 'friend_id'

app/models/friendlist.rb
class Friendlist < ActiveRecord::Base
  attr_accessible :friend_id, :friend_staus, :user_id
  belongs_to :user
  belongs_to :friend, :class_name => 'User', :foreign_key =>'friend_id'
 
  scope :accepted, -> { where friend_staus: 'accepted'} 
  scope :rejected, -> { where friend_staus: 'rejected'}
  scope :invited, -> { where friend_staus: 'invited'}
end

app/models/picture.rb
class Picture < ActiveRecord::Base
 
  attr_accessible :image, :imageable_id, :imageable_type, :user_id
  belongs_to :imageable, :polymorphic => true
  belongs_to :user
  mount_uploader :image, ImageUploader
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :status, :user_id, :pictures_attributes, :ratings_attribute
  has_many :pictures, :as => :imageable
  has_many :ratings, :as => :ratingable
  has_many :comments, :dependent => :destroy
  belongs_to :user
  accepts_nested_attributes_for :pictures, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendlists, :dependent => :destroy
  has_many :friends, :through => :friendlists, :conditions => "friend_staus = 'accepted'"
  has_many :pictures, :as => :imageable
  has_many :myfriend, :through => :friends, :source => "Friend"
  has_many :posts
  has_many :comments
  has_many :ratings
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :date_of_birth, 
    :contact, :hobby, :home_town, :state, :country, :relationship_status, :interest_in, :language, :religion, :gender,
    :pictures_attributes

  accepts_nested_attributes_for :pictures, :allow_destroy => true

  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
   
   def after_sign_in_path_for(resource)
    '/users/welcome'
   end
   
end

app/controllers/friendlists_controller.rb
class FriendlistsController < ApplicationController

   

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  
  
  def friend
    @friend = Friend.new
  end 
  
 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post=Post.new
    @friendlists = Friendlist.new
    @post.pictures.build
  end
  
  def index
    @post = Post.new
    @user=User.all
    @post.pictures.build
    friend_ids = current_user.friends.pluck(:id)
    friend_ids << current_user.id
    @posts = Post.where("user_id IN (?)", friend_ids)
  end
  
  def create
   @post = current_user.posts.build(params[:post])
    if(@post.save)
      redirect_to posts_path 
    end
  end

  def add_comment
    @post=Post.find(params[:p_id])
    @comment = @post.comments.new(:user_id=>current_user.id, :content=>params[:text])
    if(@comment.save)
      render :text => "comment"
    end
  end
  
  def add_likepost
    @post=Post.find(params[:p_id])
    rating = @post.ratings.where(:user_id => current_user.id).first
    if rating  
      rating.update_column(:like, false)
      render :text => "post unlike"
    else  
      @post.ratings.create(:user_id=>current_user.id, :like=>true)
      render :text => "post liked"
    end
  end
  
  def add_likecomment
    @comment=Comment.find(params[:p_id])
    rating =@comment.ratings.where(:user_id => current_user.id).first
    if rating  
      rating.update_column(:like, false)
      render :text => "comment unlike"
    else  
      @comment.ratings.create(:user_id=>current_user.id, :like=>true)
      render :text => "comment liked"
    end
  end
  
  def userinfo
    @user = User.where(:id => current_user.id).first
  end
  
  def friendinfo
    @user = User.find(params[:id])
    @friendlists = @user.friendlists.where(:friend_staus => "accepted")
  end
  
  def destroy
    @post=Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def home
    @user = User.new
  end
  
  def new
    @user=User.new
    @user.pictures.build
  end
  
  def welcome
    @users = User.where(:first_name => params[:first_name])
    if @users.present?
      flash[:notice] = "find match"
    else
      flash[:error] = "No match"
    end
  end
  
  def sendrequest
    @friendlists=Friendlist.new(:user_id => params[:id], :friend_id => current_user.id, :friend_staus =>"invited")
    if @friendlists.save
      redirect_to welcome_users_path
    end
  end
  
  def getrequest
    @friendlists = Friendlist.where(:user_id => current_user.id)
  end
  
  def replyrequest
    @friendlist = Friendlist.where(:friend_id => params[:friend_id]).first
    if @friendlist.present?
      @friendlist.update_column(:friend_staus, "accepted")
      Friendlist.create!(:user_id => @friendlist.friend_id, :friend_id => @friendlist.user_id, :friend_staus => "accepted")
      render :text => "done"
    else
      render :text => "error"
    end
  end
  
  def deleterequest
    @friendlist = Friendlist.where(:friend_id => params[:id]).first
    if @friendlist.present?
       @friendlist.update_column(:friend_staus, "rejected")
       redirect_to welcome_users_path
    end
  end
  
  def edituser
    @user =User.find(params[:id])
  end
  
  def updateuser
    @user = User.where(:id =>current_user.id).first
    if @user.update_attributes(params[:user])
      redirect_to  userinfo_posts_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
 
  def commentpost_like(id)
    Rating.where(:user_id => current_user.id, :ratingable_id => id).first 
  end
    
  def friend_image(id)
    @user=User.where(:id => id).first
  end
  
end

app/helpers/friendlists_helper.rb
module FriendlistsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendlists/addfriend.html.erb
<h1>Friend</h1>
Name:<%= current_user.first_name %>&nbsp;
Email:<%= current_user.email %>
<%= form_for(@friendlists) do |f| %>
  <input type="hidden" value=@user.id>
  <%= f.submit "invite"%>
<% end %>
  

 
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "App3" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">toc.com</a>
          <div class="container-fluid nav-collapse">
            <div class="pull-right">
            <ul class="nav nav-tabs nav-justified">
              <% if current_user.present?%>
              <li><div style="width:50px; height:50px;">
                    <a class="navbar-brand" href="/posts/userinfo" >
                      <%= image_tag(current_user.pictures.last.image_url) if current_user.pictures.present?%>
                    </a>
                 </div>
              </li>
              <li><%= link_to "Signout", "/users/sign_out", method: 'DELETE' %></li>
              <%else%>
              <li><%= link_to "Home", "/"  %></li>
              <li><%= link_to "Signin", "/users/sign_in"  %></li>
              <%end%>
            </ul>
            </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <% if current_user.present?%>
               <li class="nav-header"><%= current_user.first_name %></li>
              <li><div style="width:50px; height:50px;">
                    <a class="brand" href="/posts/userinfo" >
                      <%= image_tag(current_user.pictures.last.image_url) if current_user.pictures.present?%>
                    </a>
                 </div>
              </li>
              <li><%= link_to "User-Profile", "/posts/userinfo"  %></li>
              <li><%= link_to "Find-Friend", "/users/welcome"  %></li>
              <li><%= link_to "Notification", "/users/getrequest"  %></li>
              <li><%= link_to "View-Post", "/posts"  %></li>
              <%end%>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>

app/views/posts/index.html.erb
<div class="page-header">
  <h2>Post  <small>User</small></h2>
</div>
<%= render :partial=> 'posts/index' %>
<br>
<% @posts.each do |p| %>
  <div class="span9  well well-large">
    <div class="panel panel-danger">
      <div class="horizontalRule">
      </div>
      <div class="span11  well well-small">
        <div class="pull-right">
          <div style="width:40px; height:40px;">
            <%= image_tag(p.user.pictures.last.image_url) %>
            <span class="label label-info"><%= p.user.first_name %></span>
          </div>
         </div>
      </div><br><br><br><br>
      <%= p.status %><br>
      <% p.pictures.each do |pic| %>
        <%= image_tag(pic.image_url) if pic.image.present?%></br><br>
      <% end %>
      <%= link_to "remove", p, :method => :delete %>
      <%= image_tag "like3.jpg" %>
      <span class="badge"><%= p.ratings.count %></span>
      <%if commentpost_like(p.id) %>
        <div class="pull-right">
          <input type="button" value="dislike" id="<%= p.id%>" class="like_post" ></br><br>
        </div>
      <%else%>
        <div class="pull-right">
          <input type="button" value="like" id="<%= p.id%>" class="like_post" ></br><br>
        </div>
      <%end%>
      <% p.comments.each do |c| %>
        <div class="span11  well well-small">
          <%= c.content %>
          <div style="width:30px; height:30px;" class="pull-right">
            <%= image_tag(c.user.pictures.last.image_url) %>
            <span class="label label-info"><%= c.user.first_name %></span>
          </div>
        </div>
        <div class="pull-right">
          <%= image_tag "like3.jpg" %>
          <span class="badge"><%= c.ratings.count %></span>
          <%if commentpost_like(c.id) %>
            <input type="button" value="dislike" id="<%= c.id%>" class="like_comment" >
          <%else%>
            <input type="button" value="like" id="<%= c.id%>" class="like_comment" >
          <%end%>
        </div>
      <% end %>
      <div class="span11 well well-small">
        <input type="text" id="box_<%= p.id%>" class="textbox" >
        <input type="button" value="comment" id="<%= p.id%>" class="comment" >
      </div>
    </div>
  </div>
<% end %>

<script type="text/javascript" >

   $('.comment').click(function(form){
     var id = (this.id);
     var text_val= $('#box_'+id).val();
     $.ajax({
       type: 'POST',
       url: '/posts/add_comment',
       data: {text: text_val, p_id: id}
     }).done(function(ret){
       $('#myspan_'+id).append(ret);
     });
   });
   
   $('.like_post').click(function(form){
     var id = (this.id);
     $.ajax({
       type: 'POST',
       url: '/posts/add_likepost',
       data: {p_id: id}
     }).done(function(data,status){
     if(status=="success"){
       }
  });
 });

   $('.like_comment').click(function(form){
     var id = (this.id);
     $.ajax({
       type: 'POST',
       url: '/posts/add_likecomment',
       data: {p_id: id}
     }).done(function(data,status){
     if(status=="success"){
      }
  });
 });
 
</script>

app/views/posts/new.html.erb
<div class="page-header">
  <h2>Post <small>Create</small></h2>
</div>
<%= nested_form_for(@post) do |f| %>
  <%= f.text_area :status, :cols => 50, :rows => 5%>
  <div>
  <%= f.fields_for :pictures do |pic| %>
    <%= pic.file_field :image %>
    <%= pic.hidden_field :user_id, :value => current_user.id %>
  <% end %>
  </div>
  <%= f.submit "Post" %></br>
<% end %>

app/views/posts/show.html.erb
<h1>User Post</h1>
<%= form_for :post, :url => {:action => :userpost} do |f| %>

  <%= f.text_area :status, :cols => 50, :rows => 5%>
  <%= f.submit "Post" %></br>
  <span class="label label-info">Like</span>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :encrypted_password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :encrypted_password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_token, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_token, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :reset_password_sent_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :remember_created_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :remember_created_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :current_sign_in_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :last_sign_in_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date_of_birth, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :date_of_birth, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :contact, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :contact, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :hobby, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :hobby, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :home_town, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :home_town, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :relationship_status, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :relationship_status, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :interest_in, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :interest_in, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :language, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :language, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :religion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :religion, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gender, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :gender, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/addfriend.html.erb
<%= form_for(@user, :url => sendrequest_user_path) do |f| %>
  <input type="hidden" name="user_id "value=@user.id>
  <%= f.submit "invite"%>
<% end %>
  

 
 

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/home.html.erb
<%= image_tag "toc1.jpg" %>


  

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:date_of_birth) %></th>
      <th><%= model_class.human_attribute_name(:contact) %></th>
      <th><%= model_class.human_attribute_name(:hobby) %></th>
      <th><%= model_class.human_attribute_name(:home_town) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:relationship_status) %></th>
      <th><%= model_class.human_attribute_name(:interest_in) %></th>
      <th><%= model_class.human_attribute_name(:language) %></th>
      <th><%= model_class.human_attribute_name(:religion) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.date_of_birth %></td>
        <td><%= user.contact %></td>
        <td><%= user.hobby %></td>
        <td><%= user.home_town %></td>
        <td><%= user.state %></td>
        <td><%= user.country %></td>
        <td><%= user.relationship_status %></td>
        <td><%= user.interest_in %></td>
        <td><%= user.language %></td>
        <td><%= user.religion %></td>
        <td><%= user.gender %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/sendrequest.html.erb
hhjdfk'kdgae'kz

app/views/users/update.html.erb
friend

app/views/users/welcome.html.erb
<div class="page-header">
  <h2>Find  <small>Friend</small></h2>
</div>

<%= form_tag(welcome_users_path, method: 'GET') do %>
  <div class="navbar navbar-fluid-top">
    <div class="span11  well well-small">
      <%= text_field_tag :first_name ,placeholder="Search" %>
      <%= button_tag "Submit", :class => "btn btn-default" %>
    </div>
  </div></br></br></br></br></br></br>
<% end %>
  
<% @users.each do |user|%>
  <% if !(user.id==current_user.id ) && user.present? %>
    <table width="100%" border="1" class= "table table-striped">
      <tr>
        <th>FirstName</th>
        <th>LastName</th>
        <th>Email</th>
        <th>FriendRequest</th>
      </tr>
      <div class="panel panel-default">
        <div class="panel-heading"></div>
          <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td>
              <div id ="inivitation">
                <%if current_user.friendlists.blank? %> 
                  <%= link_to "invit","#","data-user-id" => user.id, :class => "invite"%>        
                <%else%>
                  <%= user.friendlists.first.friend_staus %>
                <%end%> 
              </div>
            </td>
          </tr>
    </table>
  <%end%>
<% end %>

<script>
  $('.invite').click(function(form){
     var friend_id = $(this).data("user-id")
     $.ajax({
       type: 'GET',
       url: '/users/sendrequest',
       data: { id: friend_id}
     }).done(function(data,status){
       if(status=="success"){
        $("#inivitation").html("alreadyinvited");
       }
     });
   });
</script>

            